services:
  - type: web
    name: ortho-list-app   # change this to your app name
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    plan: free
    autoDeploy: true
